### PR TITLE
Remove debug log prints

### PR DESCRIPTION
**Pull request by saltedpotatos**
Data table is a little too chatty in debug mode.

### CODE REVIEW

**Comment by maxim-saplin** [comment]
I'd prefer that to be configurable, tables can be slow to build

**Comment by saltedpotatos** [comment]
Ah, I guess I must have pretty simplistic tables. I can adjust the PR to place the print(s) behind a verbose flag

**Comment by saltedpotatos** [comment]
PR updated!

**Comment by maxim-saplin** [comment]
Changed it to default on and global variable (rather than constructor param). Can be turned off via entry point:

```
void main() {
  runApp(MyApp());
  dataTableShowLogs = false;
}
```

**Comment by saltedpotatos** [comment]
Awesome, thanks!

**Pull request merged**
