### PR TITLE
Expose horizontal controller

### PR DESCRIPTION
**Pull request by martinpelli**
Added horizontalScrollController to
- DataTable2
- PaginatedDataTable2
- AsyncPaginatedDataTable2

Renamed old scrollController parameter to verticalScrollController

### CODE REVIEW

**Comment by maxim-saplin** [comment]
Renaming old scroll controller is not a good idea, it is a breaking change. Please keep it with old na,e

**Comment by maxim-saplin** [comment]
Coud you please close this PR and a clean one? There're so many changes which do not make sense considering the minority of the change. Please pay attention and don't make meaningless changes such as formatting - it makes reviewing the PR a painful experience

**Comment by martinpelli** [comment]
Sorry don't know what you want, I just added the new controller in the neessary places, otherwise code will be break. there is no formatting, don't know what you are talking about. Maybe it will be better that you make the change so I can learn what you need for next time.

**Comment by maxim-saplin** [comment]
There're 11 files changed, some changes do not seem to have any point to me:

image

IMO 3-4 files maximum should be affected, not the entire solution. What I suggest is create a clean PR without the history of renaming the scroll controllers back and avoiding unnecessary changes

**Pull request closed without merging**
