### PR TITLE
dataTableShowLogs to be optional

### PR DESCRIPTION
**Pull request by MaeF41**
* dataTableShowLogs to be optional.

### CODE REVIEW

**Comment by maxim-saplin** [comment]
What is the point for the change?

**Comment by MaeF41** [comment]
I would like to reduce the noise in the terminal as I have multiple logs being printed. It would help with the readability and over all size of the logs in the terminal if that makes sense.

btw Thank you for this package!

**Comment by maxim-saplin** [comment]
But it can be disabled via the global variable which you moved as a property to DataTable2) I don't see point moving things around and inflating the list of constructor params for no reason, there're plenty already

**Comment by MaeF41** [comment]
ah that makes sense. TY

**Comment by MaeF41** [comment]
@maxim-saplin 
However, having multiple tables in one screen, it would be nice to control in the codebase what is being logged and what is not. Currently, the log says DataTable2 so I can not make the distinction.
This is not necessarily blocking me from anything, so decided to close the PR. TY

**Comment by maxim-saplin** [comment]
Do you actually have 2 tables in the screen and need fine-grained logging of the kind? IMO, current logs are rudimentary and don't provide much of insights, hence the current approach

**Pull request closed without merging**
