### PR TITLE
Add scroll physics control over data table (fix pull-refresh)

### PR DESCRIPTION
**Pull request by Pana-g**
This helps when you want to add a pull to refresh functionality and your table has few items and scroll event won't trigger, you can set `physics: AlwaysScrollableScrollPhysics(),` .

### CODE REVIEW

**Comment by maxim-saplin** [comment]
How is the suggested feature different in end result from this approach?

```
 ScrollConfiguration(
          behavior: const ScrollBehavior()
              .copyWith(physics: const ClampingScrollPhysics()),
          child: DataTable2(
```

**Comment by Pana-g** [comment]
### Current behavior
<details>

  <summary>Code:</summary>

```dart
import 'dart:math';

import 'package:data_table_2/data_table_2.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<DataRow> listA;

  @override
  void initState() {
    refreshList(50);
    super.initState();
  }

  refreshList(int number) {
    setState(() {
      listA = List<DataRow>.generate(
          number,
          (index) => DataRow(cells: [
                DataCell(Text('A' * (10 - index % 10))),
                DataCell(Text('B' * (10 - (index + 5) % 10))),
                DataCell(Text('C' * (15 - (index + 5) % 10))),
                DataCell(Text('D' * (15 - (index + 10) % 10))),
                DataCell(Text(((index + 0.1) * 25.4).toString()))
              ]));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Padding(
            padding: const EdgeInsets.all(16),
            child: RefreshIndicator(
              onRefresh: () {
                return Future.delayed(
                    Duration.zero, () => refreshList(Random().nextInt(5) + 5));
              },
              child: DataTable2(
                  columnSpacing: 12,
                  horizontalMargin: 12,
                  minWidth: 600,
                  columns: const [
                    DataColumn2(
                      label: Text('Column A'),
                      size: ColumnSize.L,
                    ),
                    DataColumn(
                      label: Text('Column B'),
                    ),
                    DataColumn(
                      label: Text('Column C'),
                    ),
                    DataColumn(
                      label: Text('Column D'),
                    ),
                    DataColumn(
                      label: Text('Column NUMBERS'),
                      numeric: true,
                    ),
                  ],
                  rows: listA),
            )));
  }
}

```

</details>

<details>

  <summary>Video:</summary>

[issue.webm](https://user-images.githubusercontent.com/21154472/212296063-7cc7150d-eaae-453c-a49e-4581ca3c7fb2.webm)

</details>

### Proposed solution behavior

<details>

  <summary>Code:</summary>

```dart
import 'dart:math';

import 'package:data_table_2/data_table_2.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<DataRow> listA;

  @override
  void initState() {
    refreshList(50);
    super.initState();
  }

  refreshList(int number) {
    setState(() {
      listA = List<DataRow>.generate(
          number,
          (index) => DataRow(cells: [
                DataCell(Text('A' * (10 - index % 10))),
                DataCell(Text('B' * (10 - (index + 5) % 10))),
                DataCell(Text('C' * (15 - (index + 5) % 10))),
                DataCell(Text('D' * (15 - (index + 10) % 10))),
                DataCell(Text(((index + 0.1) * 25.4).toString()))
              ]));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Padding(
            padding: const EdgeInsets.all(16),
            child: RefreshIndicator(
              onRefresh: () {
                return Future.delayed(
                    Duration.zero, () => refreshList(Random().nextInt(5) + 5));
              },
              child: DataTable2(
                  // ADDITIONAL LINE 
                  physics: const AlwaysScrollableScrollPhysics(),
                  columnSpacing: 12,
                  horizontalMargin: 12,
                  minWidth: 600,
                  columns: const [
                    DataColumn2(
                      label: Text('Column A'),
                      size: ColumnSize.L,
                    ),
                    DataColumn(
                      label: Text('Column B'),
                    ),
                    DataColumn(
                      label: Text('Column C'),
                    ),
                    DataColumn(
                      label: Text('Column D'),
                    ),
                    DataColumn(
                      label: Text('Column NUMBERS'),
                      numeric: true,
                    ),
                  ],
                  rows: listA),
            )));
  }
}



```

</details>

<details>

  <summary>Video:</summary>

[solution.webm](https://user-images.githubusercontent.com/21154472/212296503-5329aff7-7f81-403b-aa36-12fd0a1828fc.webm)


</details>

**Comment by maxim-saplin** [comment]
I see, thanks for the examples... Though I think the approach suggested is more of a workaround for one specific case - allowing pull-to-refresh work. I don't see how else that may benefit, besides what kind of side effects changing only 2 of the 4 scrollable within the widget. One of the side effects I can see is that while in docs you say that scroll physics is applied to the whole widget essentially it changes only vertical scrollable but doesn't touch the horizontal ones.

In your example pull to refresh stops working when there're few rows and vertical scrolling is no longer available. 

I think that while fixing pull-to-refresh is a good thing to do, though I am not sure the best way is by exposing 2 of the 4 scrollable via the extra field - that's what you did. IMO this is a good example that the internal structure of the widget is worth revisiting for the search of a better structure. Below you can see one more issue related to the current approach, when there're too few rows which don't fill the view port there're 2 horizontal scrollbars displayed.

image

I don't have an answer to that yet. If you have suggestions on refactoring the scrollables within data table you're welcome.

**Comment by Pana-g** [comment]
@maxim-saplin  Hm. That's interesting. I can't emulate this kind of behavior on my side. Can you please share the code for the example you provided?

**Comment by maxim-saplin** [comment]
It's your second example, it's just run under macOS

**Comment by maxim-saplin** [comment]
FYI, here's an issue which seem related: https://github.com/maxim-saplin/data_table_2/issues/140

**Pull request closed without merging**
