### PR TITLE
Update data_table_2.dart

### PR DESCRIPTION
**Pull request by hootyjeremy**
Added 'sortArrowAnimationDuration' for custom animation duration (for having instant snap upward and downward). Also added sortArrowIcon so for using different arrow icons.

I couldn't get line 1377 to work as a const. If it needs to be const, maybe I can look at it. 

These were two personal preferences that I hope don't break the widget.

### CODE REVIEW

**Comment by maxim-saplin** [comment]
Thanks for the PR!
Could you please:
1. Add widget test to` /test/custom_features_test.dart` that verified the behaviour
2. Demonstrate the feature in examples (add sub-example 'Custom arrows' to `example/lib/screens/data_table2.dart`)
3. Document public all members added

**Comment by hootyjeremy** [comment]
1) I have added tests. I've never done a unit or widget test but they did pass.
2) I just added the 'sortArrowAnimationDuration' and 'sortArrowIcon' parameters to the DataTable2() call. I wasn't sure how to add a new example. I hope this is correct.
3) Where do I need to document these? I have only given them comments where they are declared.

**Comment by hootyjeremy** [comment]
I've documented the two sort parameters in readme.md if that's okay.

**Comment by maxim-saplin** [comment]
> * I have added tests. I've never done a unit or widget test but they did pass.
> * I just added the 'sortArrowAnimationDuration' and 'sortArrowIcon' parameters to the DataTable2() call. I wasn't sure how to add a new example. I hope this is correct.
> * Where do I need to document these? I have only given them comments where they are declared.

1. Just checked your test, though it doesn't test anything as there's no single expect statement and verification for the feature. You should at least check if custom arrow is applied. Secondly you can write a test to see if the animation completes within the specified period of time (e.g. do 2 pumps with time lower and greater than the duration and checking arrow positions after each pump to see that the arrow take required position right after the period). Besides you'd rather check other tests and reuse the approach used to init data tables (i.e. use buildTable() and have it modified to create widget with new fields)

On a separate note, there're tons of formatting changes with no actual new stuff, it makes hard to read diffs:
image

2. Please note that there're routing params which enable or disable certain features. What I'm asking is to follow the approach and introduce a new routing param, as well as sub section in top right corner of the UI to specifically showcase the feature.

3. You've missed inline documentation for sortArrowIcon:
image

**Comment by hootyjeremy** [comment]
Let me cancel this PR and try to start a fresh one. I'm still new to flutter so I don't know anything about testing or any of this stuff. I'll do some cleanup here and re-submit.

**Comment by maxim-saplin** [comment]
Thanks, you're doing good so far)

**Pull request closed without merging**
