### PR TITLE
Fix for #254, How to have selected rows on table create with AsyncDataTableSource

### PR DESCRIPTION
**Pull request by MogensO**
In _fixSelectedState we need to check for an entry in _selectionRowKeys for the SelectionState.none

In _fetchData we also need to ensure that  _selectionRowKeys  are maintained for the rows retreived from getRows

### CODE REVIEW

**Comment by maxim-saplin** [comment]
It doesn't seem to be working as expected. I.e. in async data source I set rows as selected:

image

Yet the state doesn't get applied:

image

**Comment by MogensO** [comment]
This is weird.
If I do the same, I get:
image

I also tried to modify the Dessert domain model entity as shown below to simulate selected coming from the DataSource:
image
With the result being:
image

Could you eventually check your version of async_paginated_data_table_2.dart?
It should contain:
image

**Comment by maxim-saplin** [comment]
I haven't given this enough though yet it might be a good point to keep the selection state out of data source (i.e. always ignore there data source selected), I don't know. Any suggestions?

**Comment by MogensO** [comment]
Well not at the moment, I'll have to dig deeper in the code.
I'll give it a thought over the Eastern.
Anyway it is somehow a crucial function for me, as the selected state of a row   
very often is something we will persists in a database and thus must be present in the data source.

**Comment by maxim-saplin** [comment]
Conceptually the selection state look like a transient one and shouldn't be part of entity persisted...

**Comment by MogensO** [comment]
I don't really see why this should not be persisted.
If you i.e. select an order for picking in a WMS system you would certainly need to persist
that, i.e. because it signals that the order have been started  and you or someone else  would like
to see that later on somewhere else or maybe stop it again be deselecting it.
If that should be reflected somewhere else it would require a second column in the table which take up space
and essentially is redundant.
And on small handheld devices space is scarce.

**Pull request closed without merging**
