### PR TITLE
Added more properties to PaginatedDataTable2 and AsyncPaginatedDataTable2, fixed tests

### PR DESCRIPTION
**Pull request by Pana-g**
- Added `dividerThickness`
- Added `renderEmptyRowsInTheEnd` (It won't render empty rows in the end of the Table when set to `false`)
- Fixed cross platform goldens images comparison for tests, by adding custom fonts based on [this](https://api.flutter.dev/flutter/flutter_test/matchesGoldenFile.html#flutter_test.flutter_test.matchesGoldenFile.2)

### CODE REVIEW

**Comment by Pana-g** [comment]
@maxim-saplin It seems that adding custom fonts while running tests it doesn't help a lot, matchesGoldenFile keeps failing.

**Comment by maxim-saplin** [comment]
Uploaded new Goldens, PR should work. Here's side-by-side comparison, macOS renders fonts bold

image

**Comment by maxim-saplin** [comment]
There's a minor bug with `renderEmptyRowsInTheEnd`, pagination shows incorrect number of rows on the page when page size is greater than available number of rows:

image

**Comment by Pana-g** [comment]
@maxim-saplin I just made a small change that will take into consideration `renderEmptyRowsInTheEnd` when showing the footer info title. By the way I've been testing `renderEmptyRowsInTheEnd` with different properties combinations and had no issues so far.

**Comment by Pana-g** [comment]
@maxim-saplin You know that you closed it instead of merged it?

**Comment by maxim-saplin** [comment]
Oops.. Thanks for noticing. Though I've already pushed the new version to pub.dev)

**Pull request merged**
