### PR TITLE
Fix #80

### LINKED ISSUE #80: Remove highlight on row hover
I didn't see the option to remove the highlight when hovering over a row : 

Capture d’écran 2022-03-22 à 14 40 33

does this feature exist? or is there a way around this?

### PR DESCRIPTION
**Pull request by nosmirck**
fix for #80 

- Added a flag to disable hover when no gestures are added to the rows.

### CODE REVIEW

**Comment by nosmirck** [comment]
fixed merge issues!

**Comment by nosmirck** [comment]
@maxim-saplin hello! I suspect there's something failing with the release script with the PR, can you please take a look. If it's something with my code I can fix it. The whole thing looks fine up to the release where it says it can't find the url for your repo, which is weird.

**Comment by maxim-saplin** [comment]
Fixed the workflows, there shouldn't be any failures anymore. Deployment to GH Pages step was failing cause authorization issues, apparently PR shouldn't trigger a deployment..

Speaking of the PR itself, I'm still digesting the changes, I'm a bit distracted and going slow... Though I have some concerns:
1. There seem to be to much code changes for that minor issue
2. There's no test for the new code
3. The feature is present in DataTable2 but is not present in PaginatedDataTable2
4. I've got a feeling that styling/theming might be a better way to go rather than introducing another field
5. What if I want to have no hover color changing while having tap event?
6. The examples got harder to read with `rowDisabledHover` and `disableAllGestures`
7. I'm not sure if we even need a separate example for that feature, might be part of one of the existing samples

**Comment by maxim-saplin** [comment]
image
Here's how you disable row hovering. No need for any changes to sources.

**Comment by nosmirck** [comment]
What about zebra + disable hover?  I tried this:

```dart
 return DataRow2.byIndex(
      index: index,
       color: MaterialStateProperty.resolveWith((states) {
        return index.isEven ? Theme.of(context).primaryColorLight : Theme.of(context).canvasColor;
      }),
```
which works, but if I use certain colors like highlightColor or selectedColor, from the theme it changes on hover (maybe there are some rules on the gestures that if some of these colors are detected it changes?)

Anyways, the only issue I can't seem to solve is the fact that, on web desktop, the cursor shows as interactive (the hand icon cursor) like if you could interact with the table, which is what we are looking to disable)

This is not just a case of not making the rows change colors when hovering, it is a case of not having any interaction on the rows when no interaction has been set (selection, tap, long tap, etc)

If there's not a single gesture set to interact with the rows, there's no need to highlight them when the cursor hovers.

**Comment by maxim-saplin** [comment]
Once again, thanks for the contribution. Should you have time and desire to work on some other pieces of the package - let me know!

**Pull request closed without merging**
