### PR TITLE
Added fixed columns and rows control properties in PaginagedDataTable 2 and AsynPaginatedDataTable2

### PR DESCRIPTION
**Pull request by Pana-g**

### CODE REVIEW

**Comment by maxim-saplin** [comment]
I get failed tests here as well. Did you run tests locally?

image

**Comment by Pana-g** [comment]
@maxim-saplin Yes I do run them locally. This is the same reason why tests in my other PR failed. It's because of goldens image comparison. In my machine all tests run successfully.

**Comment by Pana-g** [comment]
@maxim-saplin Yes that could be an environment issue since I'm working with Linux. 
The output of `flutter doctor` :
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on Ubuntu 22.04.1 LTS 5.15.0-56-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by maxim-saplin** [comment]
It seems that on Linux golden files/UI is rendered with smooth/blurry lines

**Comment by maxim-saplin** [comment]
Thanks for the contribution!

**Pull request merged**
