### PR TITLE
Lints, enhancements and bug fixes

### PR DESCRIPTION
**Pull request by nosmirck**
Hello, great package!

I needed a couple of things so I took some time to give some love to this package.

First of all, I updated a couple of dependencies (async and vector_math) I don't think it was 100% needed, but still did it just in case the package can take advantage of any improvements done there.

Then I added flutter_lints, I thought it would help get more pub.dev points! And also solved all over 300 issues (warnings) that came with it.

Then I added a simple improvement, the column size for DataColumn2 is very helpful, but very limited to be honest, so, I added a couple of optional parameters to it.

The first one is ratio. With it you can se any custom ratio (other than the ones set for S, M and L)
The second is absoluteSize. This one is a fixed size for the width of the column, this is very useful for those columns that have small content (like just one icon representing some status like active/inactive) and you don't want it to take too much space, so a fixed size makes sense.

I also needed to fix a few other things:
- #30 I found the issue, it was a simple fix
- #80 This one was a hard one to find, but had a simple fix too.

All tests are passing, I'll be adding tests for the absoluteSize and ratio properties I added to DataColumn2

Have a great day!

### CODE REVIEW

**Comment by nosmirck** [comment]
Oh! I just remembered I also have to add documentation for https://github.com/maxim-saplin/data_table_2/pull/87/commits/a300fc86dc106704a391ef00fd4afe2e4b5c7016

**Comment by maxim-saplin** [comment]
Hi there! Somehow I missed you PR... And did a number of upgrades (Dart 2.17, Flutter 3.0, lints) by myself. 

Could you please, close this PR, take the most recent **master** version and open new PRs for each of the 2 issues (#30, #80)?

Besides, I'm not quite sure what #80 is about - could you please elaborate in the issue?

**Comment by nosmirck** [comment]
Hello @maxim-saplin sure thing, I'll do that!

#80 basically happens because of [this param](https://github.com/maxim-saplin/data_table_2/blob/545e00371c722841b6aac9e82a936d04b45ed147/lib/src/data_table_2.dart#L330) that should be nullable, since not always we want to give a gesture to the rows, if we don't have any gesture set, there's no need to set a onSelectChanged callback, However, if you see [this line](https://github.com/maxim-saplin/data_table_2/blob/545e00371c722841b6aac9e82a936d04b45ed147/lib/src/data_table_2.dart#L534) you're forcing the onSelectChanged to have a callback, in the case the actual onSelectChanged from the widget is null, you force it to be `() => null` which can be considered a no-op and does nothing, yet, because it's not a null callback and its forced [here](https://github.com/maxim-saplin/data_table_2/blob/545e00371c722841b6aac9e82a936d04b45ed147/lib/src/data_table_2.dart#L384) to add an `TableRowInkWell` we have hover highlight regardless of the gestures we set (or not set in this case)

The fix was simple, make the `onSelectChanged` for the `_buildDatCell` method nullable and change the condition to this:

```dart
    } else if (onRowTap != null || onSelectChanged != null) {
      label = GestureDetector(
        child: TableRowInkWell(
          child: label,
          overlayColor: overlayColor,
          onTap: () {
            onRowTap?.call();
            onSelectChanged?.call();
          },
          onDoubleTap: onRowDoubleTap,
          onLongPress: onRowLongPress,
        ),
```

Also, when calling `_buildDataCell` instead of forcing the callback, make it like this:

```dart
        onSelectChanged: row.onSelectChanged != null ? () => row.onSelectChanged!(!row.selected) : null,
```

That ensures not only that we have an actual onSelectedChanged callback being called only when it's not null but also doesn't add an unnecessary InkWell to the Row.

**Comment by maxim-saplin** [comment]
Thanks! Let's move the discussion of #80 to the ticket itself. I'm still not sure what is the trouble. Regarding the nullable onSelectChanged, there might be reason why it is not so, need to investigate. What I do remember is that in the stock widgets there was no row level tap events and I had to do some tricks to have it added.

Closing this PR and waiting for 2 new PRs.

**Pull request closed without merging**
