### PR TITLE
Add more properties in PaginatedDataTable2

### PR DESCRIPTION
**Pull request by Pana-g**
Add the following properties to PaginatedDataTable2 for more customizability
- dividerThickness
- fixedLeftColumns
- fixedColumnsColor
- fixedCornerColor

### CODE REVIEW

**Comment by maxim-saplin** [comment]
Thanks for the changes. It'd be great if you added test for this new fields, to make sure this pass through of DataTable2 values don't break anything when displayed within the structure of paginated table

**Comment by Pana-g** [comment]
@maxim-saplin Tests have been updated!

**Comment by maxim-saplin** [comment]
I believe you've added only dividerThickness test. fixed*** fields are not tested, yet that's the most complicated stuff. 

Besides, I've just noticed you didn't pass through fixedHeaderColumns param which is part of the complete set of fields controlling how fixed sections work

**Comment by Pana-g** [comment]
@maxim-saplin  There is no `fixedHeaderColumns` param. Maybe you mean `fixedTopRows` ?

**Comment by maxim-saplin** [comment]
My bad, fixedTopRows

**Comment by Pana-g** [comment]
@maxim-saplin I added `fixedTopRows` in `paginated_data_table` and in `async_paginated_data_table` alongside the rest of the parameters that control the fixed sections.

**Comment by Pana-g** [comment]
Hi @maxim-saplin ! I also added a new param in `paginated_data_table_2` called `renderEmptyRowsInTheEnd` that will prevent the rendering of empty rows in the end of a table when set to `false` in case of `visible rows < rowsPerPage`

**Comment by maxim-saplin** [comment]
Something is deftly wrong with the latest changes, tests fail. I'd recommend do the following:
1. Remove the renderEmptyRowsInTheEnd and dividerThickness from this PR, make them a separate ones
2. Have this PR only dealing with fixed rows and cols
3. Add a new example for paginated table replicating [data_table2_fixed_nm.dart](https://github.com/maxim-saplin/data_table_2/blob/main/example/lib/screens/data_table2_fixed_nm.dart) and available as a sub example of Fixed Rows/Cols example (when there's a second dropdown to the right with option to choose between DataTable2 and PaginatedDataTable2)
4. Take https://github.com/maxim-saplin/data_table_2/blob/main/test/fixed_rows_cols_test.dart as a basis for unit tests checking for new features in AsynPaginatedDataTable2

**Comment by Pana-g** [comment]
Hi @maxim-saplin I've created a new pull request for fixed columns and rows control properties #157 . I'll create a new one for `renderEmptyRowsInTheEnd` and `dividerThickness` asap and then I'll discard this PR.

**Pull request closed without merging**
